# Generated by Django 2.1 on 2018-08-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_prices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprices',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
