# Generated by Django 2.1 on 2018-08-09 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('symbol', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
